In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

TODO #1


In [3]:
a = np.array([1, 2, 3, 4, 5])
print('a: ', type(a))

a:  <class 'numpy.ndarray'>


TODO #2

In [4]:
a = np.random.rand(4, 4)
print(a)

[[0.59714086 0.65760864 0.7582676  0.72396884]
 [0.90293543 0.22170405 0.96341602 0.64069489]
 [0.77846027 0.00993084 0.23513818 0.14821554]
 [0.05585461 0.58782985 0.05472929 0.58291747]]


TODO #3

In [10]:
a = np.matrix(np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]))
print(a)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]]


TODO #4

In [12]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]
